[package]
name = "raster"
version = "0.1.0"
authors = ["Guangchen Li <guangchenli96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.17.0"
tobj = "2.0.2"
nalgebra = "0.21.1"
rand = "0.7.3"